import type { TaskPresentation } from "@/shared/model/taskPresentation";

export const aioTaskPresentation: TaskPresentation = {
  stages: {
    draft: "准备任务",
    checking: "检查中",
    check_failed: "检查失败",
    ready: "等待执行",
    queued: "排队中",
    prepare_config: "读取发布配置",
    prepare_artifact: "准备镜像文件",
    prepare_release: "生成发布包",
    prepare_target: "准备一体机配置",
    prepare_lease: "确认任务可执行",
    prepare_lease_failed: "任务执行条件确认失败",
    prepare_local: "准备发布文件",
    prepare_remote: "准备一体机",
    lease_acquired: "已确认可以执行",
    ssh_connect: "连接一体机",
    ssh_connected: "连接完成",
    upload: "上传发布文件",
    prepare_agent: "准备执行脚本",
    precheck: "检查运行环境",
    backup: "备份现有数据",
    install: "安装发布包",
    register: "确认平台注册",
    health: "检查服务状态",
    service_check: "检查目标服务",
    service_inspection: "读取服务和镜像",
    inspect_services: "读取服务和镜像",
    service_upgrade: "升级目标服务",
    service_health: "检查目标服务状态",
    remote_complete: "一体机操作完成",
    finalizing: "保存执行结果",
    completed: "已完成",
    cancelling: "正在取消",
    cancelled: "已取消",
    failed: "执行失败",
    preparation_failed: "准备失败",
    submission_failed: "任务提交失败",
    handler_failed: "任务处理失败",
    needs_reconcile: "等待结果确认",
    interrupted: "执行中断",
    preflight_target: "检查一体机"
  },
  canRetryResult: (task) => ["first_deploy", "full_upgrade", "service_upgrade"].includes(task.operationType)
};
